### ISSUE TITLE
Add swap for wgEnableAPI and wgEnableWriteAPI

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/mw-tool-tourbot#14]
For example:

```js
if (wgEnableWriteAPI) {}
if ( !wgEnableWriteAPI ) {}
if ( !mw.config.get( 'wgEnableAPI' ) ) { return; }
if (!document.editform || !window.wgEnableAPI || !wgEnableAPI ) { return false; } 
if (!wlUnwatch.supported || !mw.config.get('wgEnableWriteAPI')) {}
if(mw.config.get('wgCanonicalSpecialPageName') == 'Contributions' && mw.config.get('wgEnableAPI')) { }

var wgEnableAPI = true; var wgEnableWriteAPI = true; // red herring
```

Could become something like this:

```js
if (true) {}
if ( false ) {}
if ( false ) { return; }
if (!document.editform || false || false ) { return false; } 
if (!wlUnwatch.supported || false) { wlUnwatch.supported = false; }
if(mw.config.get('wgCanonicalSpecialPageName') == 'Contributions' && true) { }

var wgEnableAPI = true; var wgEnableWriteAPI = true; // red herring
```

See:
* [Global search results](https://tools.wmflabs.org/global-search/?q=(wgEnableAPI|wgEnableWriteAPI)&regex=1&namespaces=2,4,8)
* https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/504076/
* https://meta.wikimedia.org/wiki/Tech/News/2019/25
* <https://www.mediawiki.org/wiki/RL/MGU#wgEnableAPI>

/cc @Krenair, @jdforrester

**Comment by DannyS712** [comment]
What about if `window.mw.config.get()`? Eg [1] - `if (!window.mw.config.get('wgEnableAPI') || !window.mw.config.get('wgEnableWriteAPI')) {`

[1] https://ar.wikipedia.org/wiki/مستخدم:عبد_الله/common.js

**Comment by Krinkle** [comment]
Thanks @DannyS712!

I've updated my bot and am now slowly going through the search results and seeing if each replacement is correct. You can see some of the results via my [Global user contributions](https://tools.wmflabs.org/guc/?src=rc&by=date&user=Krinkle).

**Comment by DannyS712** [comment]
> Thanks @DannyS712!
> 
> I've updated my bot and am now slowly going through the search results and seeing if each replacement is correct. You can see some of the results via my [Global user contributions](https://tools.wmflabs.org/guc/?src=rc&by=date&user=Krinkle).

Glad I could help. I noted an edge case above that may not be solved
